
create table if not exists advertisements (

id bigint generated by default as identity primary key,

company_name text,

website text,

email text,

phone text,

category text,

details text,

status text default 'pending',

created_at timestamp default now()

);


