create table if not exists advertisements (

id bigint generated by default as identity primary key,

business_name text not null,

contact_name text,

email text,

phone text,

website text,

category text,

description text,

image_url text,

status text default 'pending',

created_at timestamp default now()

);



create table if not exists ad_views (

id bigint generated by default as identity primary key,

advertisement_id bigint references advertisements(id),

page text,

created_at timestamp default now()

);



alter table advertisements enable row level security;


create policy "Anyone can submit ads"
on advertisements
for insert
with check (true);


create policy "Anyone can view approved ads"
on advertisements
for select
using (status='approved');


create policy "Admins manage ads"
on advertisements
for all
using (
exists (
select 1 from profiles
where profiles.id = auth.uid()
and profiles.role='admin'
)
);
