create table if not exists advertisements (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

business_name text,

category text,

description text,

website text,

email text,

status text default 'pending',

created_at timestamp default now()

);



alter table advertisements enable row level security;



create policy "Users submit advertisements"

on advertisements

for insert

with check(auth.uid()=user_id);



create policy "Users view own advertisements"

on advertisements

for select

using(auth.uid()=user_id);

