create table if not exists affiliates (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

affiliate_code text unique,

status text default 'active',

created_at timestamp default now()

);



alter table affiliates enable row level security;



create policy "Users view own affiliate"

on affiliates

for select

using(auth.uid()=user_id);



create policy "Users create affiliate"

on affiliates

for insert

with check(auth.uid()=user_id);




create table if not exists affiliate_clicks (

id bigint generated by default as identity primary key,

affiliate_id bigint references affiliates(id),

page text,

created_at timestamp default now()

);



alter table affiliate_clicks enable row level security;



create policy "Public affiliate clicks"

on affiliate_clicks

for insert

with check(true);




create table if not exists affiliate_commissions (

id bigint generated by default as identity primary key,

affiliate_id bigint references affiliates(id),

amount numeric default 0,

source text,

status text default 'pending',

created_at timestamp default now()

);



alter table affiliate_commissions enable row level security;



create policy "Affiliate view commissions"

on affiliate_commissions

for select

using(true);

