create table if not exists ai_messages (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

question text,

answer text,

created_at timestamp default now()

);



alter table ai_messages enable row level security;



create policy "Users view own AI messages"

on ai_messages

for select

using(auth.uid()=user_id);



create policy "Users create own AI messages"

on ai_messages

for insert

with check(auth.uid()=user_id);

