create table if not exists ai_tutor_sessions (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

lesson_id bigint references lessons(id),

question text,

answer text,

created_at timestamp default now()

);



alter table ai_tutor_sessions enable row level security;



create policy "Users view own tutor sessions"

on ai_tutor_sessions

for select

using(auth.uid()=user_id);



create policy "Users create tutor sessions"

on ai_tutor_sessions

for insert

with check(auth.uid()=user_id);




create table if not exists quizzes (

id bigint generated by default as identity primary key,

lesson_id bigint references lessons(id),

question text,

option_a text,

option_b text,

option_c text,

option_d text,

correct_answer text

);



alter table quizzes enable row level security;



create policy "Public quiz access"

on quizzes

for select

using(true);

