create table if not exists analytics_events (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

event_type text,

page text,

details text,

created_at timestamp default now()

);



alter table analytics_events enable row level security;


create policy "Anyone can create analytics"

on analytics_events

for insert

with check(true);



create policy "Admins view analytics"

on analytics_events

for select

using(

exists(

select 1 from profiles

where profiles.id=auth.uid()

and profiles.role='admin'

)

);

