create table if not exists analytics_events (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

event_name text,

page text,

created_at timestamp default now()

);



alter table analytics_events enable row level security;



create policy "Users create analytics events"

on analytics_events

for insert

with check(auth.uid()=user_id);



create policy "Admins view analytics"

on analytics_events

for select

using(true);

