create table if not exists audit_logs (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

action text,

target text,

details text,

created_at timestamp default now()

);



alter table audit_logs enable row level security;



create policy "Admins view audit logs"

on audit_logs

for select

using(true);



create table if not exists security_events (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

event_type text,

ip_info text,

created_at timestamp default now()

);



alter table security_events enable row level security;



create policy "Users view own security events"

on security_events

for select

using(auth.uid()=user_id);

