create table if not exists user_activity (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

activity text,

created_at timestamp default now()

);



alter table user_activity enable row level security;



create policy "Users view own activity"

on user_activity

for select

using(auth.uid()=user_id);



create policy "Users add activity"

on user_activity

for insert

with check(auth.uid()=user_id);




create table if not exists recommendations (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

skill text,

reason text,

created_at timestamp default now()

);



alter table recommendations enable row level security;



create policy "Users view recommendations"

on recommendations

for select

using(auth.uid()=user_id);

