create table if not exists certificates (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

certificate_id text unique,

course_name text,

student_name text,

issued_at timestamp default now()

);



alter table certificates enable row level security;



create policy "Users view own certificates"

on certificates

for select

using(auth.uid()=user_id);



create policy "Users create certificates"

on certificates

for insert

with check(auth.uid()=user_id);

