create table if not exists community_posts (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

title text,

content text,

category text default 'general',

created_at timestamp default now()

);



alter table community_posts enable row level security;



create policy "Public community posts"

on community_posts

for select

using(true);



create policy "Users create posts"

on community_posts

for insert

with check(auth.uid()=user_id);




create table if not exists community_comments (

id bigint generated by default as identity primary key,

post_id bigint references community_posts(id),

user_id uuid references auth.users(id),

comment text,

created_at timestamp default now()

);



alter table community_comments enable row level security;



create policy "Public comments"

on community_comments

for select

using(true);



create policy "Users add comments"

on community_comments

for insert

with check(auth.uid()=user_id);

