create table if not exists creators (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

name text,

bio text,

expertise text,

approved boolean default false,

created_at timestamp default now()

);



alter table creators enable row level security;



create policy "Public approved creators"

on creators

for select

using(approved=true);



create policy "Users create creator profile"

on creators

for insert

with check(auth.uid()=user_id);




create table if not exists creator_courses (

id bigint generated by default as identity primary key,

creator_id bigint references creators(id),

title text,

description text,

price numeric default 0,

status text default 'pending',

created_at timestamp default now()

);



alter table creator_courses enable row level security;



create policy "Public approved courses"

on creator_courses

for select

using(status='approved');

