create table if not exists student_stats (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id) unique,

points integer default 0,

streak integer default 0,

badges text default 'Starter',

last_activity timestamp default now()

);



alter table student_stats enable row level security;



create policy "Users view own stats"

on student_stats

for select

using(auth.uid()=user_id);



create policy "Users update own stats"

on student_stats

for update

using(auth.uid()=user_id);



create table if not exists leaderboard (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

username text,

points integer default 0

);



alter table leaderboard enable row level security;



create policy "Public leaderboard view"

on leaderboard

for select

using(true);

