create table if not exists lessons (

id bigint primary key,

level text,

title_en text,

title_ur text,

content_en text,

content_ur text,

order_number integer

);



create table if not exists user_progress (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

lesson_id bigint references lessons(id),

completed boolean default false,

score integer default 0,

created_at timestamp default now()

);



insert into lessons
(id,level,title_en,title_ur,content_en,content_ur,order_number)

values


(
1,
'Beginner',
'Introduction to Online Earning',
'آن لائن کمائی کا تعارف',
'Learn the basics of earning online safely.',
'محفوظ طریقے سے آن لائن کمائی کی بنیادی معلومات حاصل کریں۔',
1
),


(
2,
'Beginner',
'Finding Your First Skill',
'اپنی پہلی مہارت تلاش کریں',
'Choose a skill that can generate online income.',
'ایسی مہارت منتخب کریں جو آن لائن آمدنی پیدا کرسکے۔',
2
),


(
3,
'Beginner',
'Create Your Profile',
'اپنا پروفائل بنائیں',
'Learn how to present yourself online.',
'آن لائن اپنا تعارف اور پروفائل بنانا سیکھیں۔',
3
),


(
4,
'Intermediate',
'Freelancing Platforms',
'فری لانسنگ پلیٹ فارم',
'Understand freelancing websites and opportunities.',
'فری لانسنگ ویب سائٹس اور مواقع کو سمجھیں۔',
4
),


(
5,
'Advanced',
'Build Digital Income',
'ڈیجیٹل آمدنی بنائیں',
'Create long-term online income systems.',
'طویل مدت کی آن لائن آمدنی کے نظام بنائیں۔',
5
)

on conflict (id) do nothing;
