create table if not exists marketplace_items (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

title text,

category text,

description text,

price numeric default 0,

type text default 'service',

status text default 'active',

created_at timestamp default now()

);



alter table marketplace_items enable row level security;



create policy "Public marketplace view"

on marketplace_items

for select

using(status='active');



create policy "Users add marketplace items"

on marketplace_items

for insert

with check(auth.uid()=user_id);




create table if not exists buyer_requests (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

request text,

created_at timestamp default now()

);



alter table buyer_requests enable row level security;



create policy "Users create requests"

on buyer_requests

for insert

with check(auth.uid()=user_id);

