create table if not exists memberships (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

plan text default 'free',

status text default 'active',

started_at timestamp default now(),

expires_at timestamp

);



alter table memberships enable row level security;


create policy "Users view own membership"

on memberships

for select

using(auth.uid()=user_id);



create policy "Users create own membership"

on memberships

for insert

with check(auth.uid()=user_id);

