create table if not exists messages (

id bigint generated by default as identity primary key,

sender_id uuid references auth.users(id),

receiver_id uuid references auth.users(id),

message text,

read boolean default false,

created_at timestamp default now()

);



alter table messages enable row level security;



create policy "Users view sent messages"

on messages

for select

using(auth.uid()=sender_id OR auth.uid()=receiver_id);



create policy "Users send messages"

on messages

for insert

with check(auth.uid()=sender_id);



create policy "Users update received messages"

on messages

for update

using(auth.uid()=receiver_id);

