create table if not exists subscriptions (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

plan text default 'free',

status text default 'active',

started_at timestamp default now(),

expires_at timestamp

);



alter table subscriptions enable row level security;



create policy "Users view own subscription"

on subscriptions

for select

using(auth.uid()=user_id);




create table if not exists payments (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

amount numeric default 0,

currency text default 'USD',

payment_type text,

status text default 'pending',

created_at timestamp default now()

);



alter table payments enable row level security;



create policy "Users view own payments"

on payments

for select

using(auth.uid()=user_id);




create table if not exists creator_earnings (

id bigint generated by default as identity primary key,

creator_id uuid references auth.users(id),

amount numeric default 0,

source text,

created_at timestamp default now()

);



alter table creator_earnings enable row level security;



create policy "Creators view earnings"

on creator_earnings

for select

using(auth.uid()=creator_id);

