create table if not exists system_logs (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

event text,

details text,

created_at timestamp default now()

);



alter table system_logs enable row level security;



create policy "Users create own logs"

on system_logs

for insert

with check(auth.uid()=user_id);



create policy "Users view own logs"

on system_logs

for select

using(auth.uid()=user_id);

