create table if not exists notifications (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

title text,

message text,

read boolean default false,

created_at timestamp default now()

);


alter table notifications enable row level security;


create policy "Users view own notifications"

on notifications

for select

using(auth.uid() = user_id);


create policy "Users receive notifications"

on notifications

for insert

with check(auth.uid() = user_id);


