create table if not exists notifications (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

title text,

message text,

type text default 'general',

read boolean default false,

created_at timestamp default now()

);



alter table notifications enable row level security;



create policy "Users view own notifications"

on notifications

for select

using(auth.uid()=user_id);



create policy "Users update own notifications"

on notifications

for update

using(auth.uid()=user_id);



create table if not exists announcements (

id bigint generated by default as identity primary key,

title text,

message text,

created_at timestamp default now()

);



alter table announcements enable row level security;



create policy "Public announcements"

on announcements

for select

using(true);

