create table if not exists opportunities (

id bigint generated by default as identity primary key,

title text,

company text,

type text default 'job',

category text,

description text,

link text,

created_at timestamp default now()

);



alter table opportunities enable row level security;



create policy "Public opportunities"

on opportunities

for select

using(true);

