create table if not exists payment_orders (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

plan text,

amount numeric,

currency text default 'USD',

payment_status text default 'pending',

transaction_id text,

created_at timestamp default now()

);



alter table payment_orders enable row level security;



create policy "Users view own payments"

on payment_orders

for select

using(auth.uid()=user_id);



create policy "Users create payments"

on payment_orders

for insert

with check(auth.uid()=user_id);

