create table if not exists user_presence (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id) unique,

status text default 'offline',

last_seen timestamp default now()

);



alter table user_presence enable row level security;



create policy "Public presence view"

on user_presence

for select

using(true);



create policy "Users update own presence"

on user_presence

for update

using(auth.uid()=user_id);

