create table if not exists referrals (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

referral_code text unique,

referred_users integer default 0,

reward_points integer default 0,

created_at timestamp default now()

);



alter table referrals enable row level security;


create policy "Users view own referrals"

on referrals

for select

using(auth.uid()=user_id);



create policy "Users create own referrals"

on referrals

for insert

with check(auth.uid()=user_id);



create policy "Users update own referrals"

on referrals

for update

using(auth.uid()=user_id);

