create table if not exists referrals (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

referral_code text unique,

created_at timestamp default now()

);



alter table referrals enable row level security;



create policy "Users view own referral"

on referrals

for select

using(auth.uid()=user_id);



create policy "Users create own referral"

on referrals

for insert

with check(auth.uid()=user_id);




create table if not exists referral_rewards (

id bigint generated by default as identity primary key,

referrer_id uuid references auth.users(id),

joined_user_id uuid references auth.users(id),

points integer default 100,

created_at timestamp default now()

);



alter table referral_rewards enable row level security;



create policy "Users view own rewards"

on referral_rewards

for select

using(auth.uid()=referrer_id);

