create table if not exists reviews (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id),

item_type text,

item_id bigint,

rating integer,

comment text,

created_at timestamp default now()

);



alter table reviews enable row level security;



create policy "Public reviews view"

on reviews

for select

using(true);



create policy "Users create reviews"

on reviews

for insert

with check(auth.uid()=user_id);



create table if not exists trust_scores (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id) unique,

score integer default 0,

updated_at timestamp default now()

);



alter table trust_scores enable row level security;



create policy "Public trust score view"

on trust_scores

for select

using(true);

