create table if not exists learning_paths (

id bigint generated by default as identity primary key,

title text,

description text,

level text,

created_at timestamp default now()

);



alter table learning_paths enable row level security;



create policy "Public learning paths"

on learning_paths

for select

using(true);




create table if not exists milestones (

id bigint generated by default as identity primary key,

path_id bigint references learning_paths(id),

title text,

order_number integer,

created_at timestamp default now()

);



alter table milestones enable row level security;



create policy "Public milestones"

on milestones

for select

using(true);

