create table if not exists student_stats (

id bigint generated by default as identity primary key,

user_id uuid references auth.users(id) unique,

points integer default 0,

streak integer default 0,

badges text default '',

updated_at timestamp default now()

);



alter table student_stats enable row level security;


create policy "Users view own stats"

on student_stats

for select

using(auth.uid() = user_id);



create policy "Users insert own stats"

on student_stats

for insert

with check(auth.uid() = user_id);



create policy "Users update own stats"

on student_stats

for update

using(auth.uid() = user_id);

